# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-12-31 02:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chess_engine', '0004_auto_20191231_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2019, 12, 31, 2, 52, 58, 59185, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
